# Generated by Django 3.2.16 on 2022-12-14 22:19

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alt_Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=150, null=True)),
                ('altkategori_isim', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0=default, 1=hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default, 1=Trending')),
                ('meta_title', models.CharField(max_length=150)),
                ('meta_keywords', models.CharField(max_length=150)),
                ('meta_descriptions', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_isim', models.CharField(max_length=150)),
                ('slug', models.CharField(blank=True, max_length=150, null=True)),
                ('kategori_aciklama', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanıcıIsim', models.CharField(max_length=150)),
                ('kullanıcıSoyisim', models.CharField(max_length=150)),
                ('ePosta', models.CharField(max_length=150)),
                ('sifre', models.CharField(max_length=150)),
                ('telNo', models.CharField(max_length=150)),
                ('kullanıcıProfilFoto', models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path)),
                ('kullanıcıPuan', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('kayıtTarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sube',
            fields=[
                ('subeID', models.BigAutoField(primary_key=True, serialize=False)),
                ('subeIsim', models.CharField(max_length=150)),
                ('sehir', models.CharField(max_length=150)),
                ('sokak', models.CharField(max_length=150)),
                ('postaKodu', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('urunID', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(blank=True, max_length=150, null=True)),
                ('urun_isim', models.CharField(max_length=150)),
                ('renk', models.CharField(max_length=150)),
                ('stok', models.IntegerField()),
                ('satis_fiyati', models.FloatField()),
                ('indirimli_satis_fiyati', models.FloatField()),
                ('stokda', models.BooleanField(default=False, help_text='0=default, 1=yok')),
                ('trendUrun', models.BooleanField(default=False, help_text='0=default, 1=Trending')),
                ('gorsel', models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path)),
                ('beden', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X Large')], default='S', max_length=2)),
                ('alt_Kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.alt_kategori')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('siparisID', models.BigAutoField(primary_key=True, serialize=False)),
                ('siparisIsim', models.CharField(max_length=150)),
                ('siparisTarihi', models.DateTimeField(auto_now_add=True)),
                ('UrunID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.urun')),
                ('kullanıcıID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.musteri')),
            ],
        ),
        migrations.CreateModel(
            name='Sepet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UrunID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.urun')),
                ('kullanıcıID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.musteri')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path)),
                ('quantity', models.IntegerField()),
                ('descriptions', models.TextField(max_length=500)),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('status', models.BooleanField(default=False, help_text='0=default, 1=hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default, 1=Trending')),
                ('tag', models.CharField(max_length=150)),
                ('meta_title', models.CharField(max_length=150)),
                ('meta_keywords', models.CharField(max_length=150)),
                ('meta_descriptions', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alt_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.alt_kategori')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Kart',
            fields=[
                ('kartNo', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('kartIsim', models.CharField(max_length=150)),
                ('bankName', models.CharField(max_length=150)),
                ('CVC', models.CharField(max_length=3)),
                ('kullanıcıID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.musteri')),
            ],
        ),
        migrations.CreateModel(
            name='Iade',
            fields=[
                ('iadeID', models.BigAutoField(primary_key=True, serialize=False)),
                ('iadeTarihi', models.DateTimeField(auto_now_add=True)),
                ('UrunID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.urun')),
                ('kullanıcıID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.musteri')),
            ],
        ),
        migrations.CreateModel(
            name='Degerlendirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urunYorum', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path)),
                ('UrunID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.urun')),
                ('kullanıcıID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.musteri')),
            ],
        ),
        migrations.AddField(
            model_name='alt_kategori',
            name='Kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.kategori'),
        ),
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sehir', models.CharField(max_length=150)),
                ('sokak', models.CharField(max_length=150)),
                ('cadde', models.CharField(max_length=150)),
                ('bina', models.CharField(max_length=150)),
                ('kullanıcıID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.musteri')),
            ],
        ),
    ]
